name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/.gitignore'

  pull_request:
    branches:
    - master

env:
  VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}\\vcpkg"
  NUGET_FEED: "https://nuget.pkg.github.com/jeff-kohn/index.json"
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/jeff-kohn/index.json,readwrite"
  NUGET_SOURCE_USERNAME: ${{ github.actor }}
  NUGET_SOURCE_PASSWORD: ${{ secrets.VCPKG_CACHE_TOKEN }}

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  msvc_build:
    name: "Window MSVC Build"
    runs-on: windows-2025-vs2026
    env:
      CONFIGURE_PRESET: "win-msvc"
      BUILD_PRESET: "win-msvc-release"
      
    steps:
    - uses: actions/checkout@v6

    - name: "Run Vcpkg"
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Add NuGet sources
      shell: pwsh
      run: |
        nuget sources add  -Source "${{ env.NUGET_FEED }}" -StorePasswordInClearText -Name GitHubPackages -UserName "${{ env.NUGET_SOURCE_USERNAME }}" -Password "${{ env.NUGET_SOURCE_PASSWORD }}"
        nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "${{ env.NUGET_FEED }}"
        dir "C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC"

    - name: Report tool versions
      shell: pwsh
      run: |
        Write-Host "## PowerShell"
        $PSVersionTable.PSVersion.ToString()
        Write-Host ""

        $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
        if (Test-Path $vswhere) {
          Write-Host "## Visual Studio"
          & $vswhere -latest -products * -property displayName
          & $vswhere -latest -products * -property installationVersion
          Write-Host ""
        }

        if (Get-Command vcpkg -ErrorAction SilentlyContinue) { Write-Host "## vcpkg"; vcpkg version; Write-Host "" } else { Write-Host "## vcpkg`nnot found in PATH`n" }
        if (Get-Command cmake -ErrorAction SilentlyContinue) { Write-Host "## cmake"; cmake --version; Write-Host "" } else { Write-Host "## cmake`nnot found in PATH`n" }
        if (Get-Command ninja -ErrorAction SilentlyContinue) { Write-Host "## ninja"; ninja --version; Write-Host "" } else { Write-Host "## ninja`nnot found in PATH`n" }
        if (Get-Command git -ErrorAction SilentlyContinue) { Write-Host "## git"; git --version; Write-Host "" } else { Write-Host "## git`nnot found in PATH`n" }
        if (Get-Command clang -ErrorAction SilentlyContinue) { Write-Host "## clang"; clang --version; Write-Host "" } else { Write-Host "## clang`nnot found in PATH`n" }
        if (Get-Command clang-cl -ErrorAction SilentlyContinue) { Write-Host "## clang-cl"; clang-cl --version; Write-Host "" } else { Write-Host "## clang-cl`nnot found in PATH`n" }
        if (Get-Command nuget -ErrorAction SilentlyContinue) { Write-Host "## nuget"; nuget help | Select-Object -First 2; Write-Host "" } else { Write-Host "## nuget`nnot found in PATH`n" }
        if (Get-Command cppcheck -ErrorAction SilentlyContinue) { Write-Host "## cppcheck"; cppcheck --version; Write-Host "" } else { Write-Host "## cppcheck`nnot found in PATH`n" }


    - name: configure
      run: |
        cmake --version
        cmake --preset=$env:CONFIGURE_PRESET

    - name: build
      run: |
        cmake --build --preset=$env:BUILD_PRESET

    - name: Upload build logs
      uses: actions/upload-artifact@v7
      if: always()
      with:
         name: msvc_vcpkg_logs
         path: |
            ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
            ${{ github.workspace }}/build/**/vcpkg-manifest-install.log
            ${{ github.workspace }}/build/**/CMakeFiles\CMakeConfigureLog.yaml
         retention-days: 3    

    - name: Upload binary
      uses: actions/upload-artifact@v7
      with:
         name: msvc_binary
         path: ${{ github.workspace }}/build/${{ env.CONFIGURE_PRESET }}/CtBrowse_app/Release/ctBrowse_app.exe
         retention-days: 30

  clang_build:
    name: "Run-Clang-Tidy"
    runs-on: windows-2025-vs2026
    env:
      PRESET_NAME: "ci-static-analysis"

    steps:
    - uses: actions/checkout@v6

    - name: "Run Vcpkg"
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Add NuGet sources
      shell: pwsh
      run: |
        nuget sources add  -Source "${{ env.NUGET_FEED }}" -StorePasswordInClearText -Name GitHubPackages -UserName "${{ env.NUGET_SOURCE_USERNAME }}" -Password "${{ env.NUGET_SOURCE_PASSWORD }}"
        nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "${{ env.NUGET_FEED }}"
        
    - name: Install pre-reqs
      run: |
        winget install CppCheck --verbose --disable-interactivity --source winget --accept-source-agreements --accept-package-agreements

    - name: Report tool versions
      shell: pwsh
      run: |
        Write-Host "## PowerShell"
        $PSVersionTable.PSVersion.ToString()
        Write-Host ""

        $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
        if (Test-Path $vswhere) {
          Write-Host "## Visual Studio"
          & $vswhere -latest -products * -property displayName
          & $vswhere -latest -products * -property installationVersion
          Write-Host ""
        }

        if (Get-Command vcpkg -ErrorAction SilentlyContinue) { Write-Host "## vcpkg"; vcpkg version; Write-Host "" } else { Write-Host "## vcpkg`nnot found in PATH`n" }
        if (Get-Command cmake -ErrorAction SilentlyContinue) { Write-Host "## cmake"; cmake --version; Write-Host "" } else { Write-Host "## cmake`nnot found in PATH`n" }
        if (Get-Command ninja -ErrorAction SilentlyContinue) { Write-Host "## ninja"; ninja --version; Write-Host "" } else { Write-Host "## ninja`nnot found in PATH`n" }
        if (Get-Command git -ErrorAction SilentlyContinue) { Write-Host "## git"; git --version; Write-Host "" } else { Write-Host "## git`nnot found in PATH`n" }
        if (Get-Command clang -ErrorAction SilentlyContinue) { Write-Host "## clang"; clang --version; Write-Host "" } else { Write-Host "## clang`nnot found in PATH`n" }
        if (Get-Command clang-cl -ErrorAction SilentlyContinue) { Write-Host "## clang-cl"; clang-cl --version; Write-Host "" } else { Write-Host "## clang-cl`nnot found in PATH`n" }
        if (Get-Command nuget -ErrorAction SilentlyContinue) { Write-Host "## nuget"; nuget help | Select-Object -First 2; Write-Host "" } else { Write-Host "## nuget`nnot found in PATH`n" }
        if (Get-Command cppcheck -ErrorAction SilentlyContinue) { Write-Host "## cppcheck"; cppcheck --version; Write-Host "" } else { Write-Host "## cppcheck`nnot found in PATH`n" }

    - name: configure
      run: |
        clang --version
        cmake --version
        cmake --preset=$env:PRESET_NAME

    - name: build clang binary
      run: |
        cmake --build --preset=$env:PRESET_NAME --target=ctBrowse_app
        
    - name: run static analysis
      run: |
        cmake --build --preset=$env:PRESET_NAME --target=code_analysis

    - name: Upload build logs
      uses: actions/upload-artifact@v7
      if: always()
      with:
         name: clang_vcpkg_logs
         path: |
            ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
            ${{ github.workspace }}/build/**/vcpkg-manifest-install.log
            ${{ github.workspace }}/build/**/CMakeFiles\CMakeConfigureLog.yaml
         retention-days: 3    

    - name: Upload binary
      uses: actions/upload-artifact@v7
      with:
         name: clang_binary
         path: ${{ github.workspace }}/build/${{ env.PRESET_NAME }}/ctBrowse_app/Release/ctBrowse_app.exe
         retention-days: 30
