name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/.gitignore'

  pull_request:
    branches:
    - master

env:
  VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}\\vcpkg"

permissions:
  contents: write
  checks: write
  packages: write

jobs:
  windows_build:
    name: "Window MSVC Build"
    runs-on: windows-2025
    env:
      CONFIGURE_PRESET: "win-clang-tidy"
      BUILD_PRESET: "win-clang-tidy-release"
      NUGET_FEED: "https://nuget.pkg.github.com/jeff-kohn/index.json"
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/jeff-kohn/index.json,readwrite"
      NUGET_AUTH_TOKEN:  ${{ secrets.VCPKG_CACHE_TOKEN }}
      NUGET_SOURCE_USERNAME: ${{ github.actor }}
      NUGET_SOURCE_PASSWORD: ${{ secrets.VCPKG_CACHE_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Set vcvars'
      uses: ilammy/msvc-dev-cmd@v1

    - name: "Setup CMake/ninja"
      uses: lukka/get-cmake@latest

    - name: "Run Vcpkg"
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Add NuGet sources
      shell: pwsh
      run: |
        nuget sources add  -Source "${{ env.NUGET_FEED }}" -StorePasswordInClearText -Name GitHubPackages -UserName "${{ env.NUGET_SOURCE_USERNAME }}" -Password "${{ env.NUGET_SOURCE_PASSWORD }}"
        nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "${{ env.NUGET_FEED }}"

    - name: Install pre-reqs
      run: |
        winget install CppCheck --verbose --disable-interactivity --source winget --accept-source-agreements --accept-package-agreements

    - name: configure
      run: |
        cmake --preset=$env:CONFIGURE_PRESET

    - name: build
      run: |
        cmake --build --preset=$env:BUILD_PRESET --target=code_analysis

    - name: Upload build logs
      uses: actions/upload-artifact@v7
      if: always()
      with:
         name: vcpkg_logs
         path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
         retention-days: 3    

    - name: Upload binary
      uses: actions/upload-artifact@v7
      if: always()
      with:
         name: vcpkg_logs
         path: ${{ github.workspace }}/build/$env:CONFIGURE_PRESET/Release/ctBrowse_app.exe
         retention-days: 3    
