name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/.gitignore'

  pull_request:
    branches:
    - master

env:
  VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}\\vcpkg"

permissions:
  contents: write
  checks: write

jobs:
  windows_build:
    name: "Window MSVC Build"
    runs-on: windows-latest
    env:
      CONFIGURE_PRESET: "ci-win-msvc"
      BUILD_PRESET: "ci-win-msvc"
      BUILD_CONFIG: "RelWithDebInfo"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Set vcvars'
      uses: ilammy/msvc-dev-cmd@v1

    - name: "Setup CMake/ninja"
      uses: lukka/get-cmake@latest

    - name: "Run Vcpkg"
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    # - name: Install winget
    #   uses: Cyberboss/install-winget@v1

    # - name: Install pre-reqs
    #   run: |
    #     winget install CppCheck --verbose --disable-interactivity  --accept-source-agreements --accept-package-agreements
    #     choco install OpenCppCoverage -y

    - name: configure
      run: |
        cmake --preset=$env:CONFIGURE_PRESET

    - name: build
      run: |
        cmake --build --preset=$env:BUILD_PRESET --config=$env:BUILD_CONFIG --target=ALL_BUILD
