name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete workflow clean runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          delete_workflow_pattern: clean

      - name: Delete failed/canceled runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_run_by_conclusion_pattern: 'cancelled,failure'

      - name: Delete old build runs
        uses: Mattraks/delete-workflow-runs@vv2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 1
          retain_days: 30
          delete_workflow_pattern: ci

  get-packages:
    name: Get Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.result }}
    steps:
      - name: Get Packages
        uses: actions/github-script@v9
        id: get-packages
        with:
          github-token: ${{ secrets.VCPKG_CACHE_TOKEN }}
          retries: 3
          script: |
            let ret = [];

            for await (const response of github.paginate.iterator(
              github.rest.packages.listPackagesForAuthenticatedUser,
              { package_type: 'nuget', per_page: 100 }
            )) 
            {
              const packages = response.data;
              for(const idx in packages) ret.push(packages[idx].name);
            }

            console.log(`Number of packages found: ${ret.length}`);
            console.log(`List of packages:`);
            console.log(ret)
            return ret;

  delete-packages:
    name: => ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: get-packages
    strategy:
      max-parallel: 3
      matrix:
        package: ${{ fromJson(needs.get-packages.outputs.packages) }}
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          token: ${{ secrets.VCPKG_CACHE_TOKEN }}
          package-name: ${{ matrix.package }}
          package-type: nuget
          min-versions-to-keep: 3
